---
title: "Comparing new vs old versions of a file"
output: html_notebook
---

## Workflow

```{r}
library(magrittr)
```


```{r}
# get id cols
# file_type <- "condition"
# uid_type <- "Sort"
# id_cols <- get_uid_cols(file_type, uid_type)
id_cols <- c("id1", "id2")
```

```{r}
# create test fixtures
# modify c1 and c2
# setwd("..")
# c1 <- load_test_file("c")
# c2 <- load_test_file("c")

base <- tibble::tibble(
  id1  = 1:4,
  id2  = LETTERS[1:4],
  num  = c(1, 2, NA_real_, 4),
  char = c(letters[1], NA_character_, letters[3:4]),
  int  = as.integer(c(1, NA_integer_, 2, 3)),
  log  = c(NA, TRUE, FALSE, NA),
  date = as.Date(c("2023-01-01", NA_character_, "2023-01-03", "2023-01-04"))
)

c1 <- base %>%
  
  # add a row not in c2
  dplyr::add_row(
    id1  = 5,
    id2  = "E",
    num  = 5,
    char = "e",
    int  = 5L,
    log  = FALSE,
    date = as.Date("2023-01-05")
  ) %>%
  
  # duplicate the added row with a different value
  dplyr::add_row(
    id1  = 5,
    id2  = "E", 
    num  = 5,
    char = "g", # this value is different
    int  = 5L,
    log  = FALSE,
    date = as.Date("2023-01-05")
  ) %>%
  
  # add a row with a NA id value
  dplyr::add_row(
    id1  = 5,
    id2  = NA_character_, 
    num  = 5,
    char = "g",
    int  = 5L,
    log  = FALSE,
    date = as.Date("2023-01-05")
  ) %>%
  
  # # add a column not in c2
  # dplyr::mutate(extra1 = rep(1, 6)) %>%
  
  # add columns with same names and values as c2 but with different classes
  dplyr::mutate(class_num_char = rep(100, 7)) %>%
  dplyr::mutate(class_num_log = rep(NA_real_, 7)) %>%

  # make a column to look at differences in decimal places and tolerance
  dplyr::mutate(
    dec_diff_ref = rep(1, 7),
    dec_diff = rep(1, 7),
  )

c2 <- base %>%
  
  # add a row not in c1
  dplyr::add_row(
    id1  = 6,
    id2  = "F",
    num  = 6,
    char = "f",
    int  = 6L,
    log  = TRUE,
    date = as.Date("2023-01-06")
  ) %>%
  
  # duplicate the first row 3x
  dplyr::bind_rows(base[1, ]) %>%
  dplyr::bind_rows(base[1, ]) %>%
  dplyr::arrange(id1, id2) %>%
  
  # # add a column not in c1
  # dplyr::mutate(extra2 = rep(2, 7))  %>%
  
  # add columns with same names and values as c1 but with different classes
  dplyr::mutate(class_num_char = rep("100", 7)) %>%
  dplyr::mutate(class_num_log = rep(NA, 7)) %>%
  
  # make a column to look a differences in decimal places and tolerance
  dplyr::mutate(
    dec_diff_ref = c(0, 0, 0, -0.0001, -0.00001, -0.000001, 0),
    dec_diff = 1 - dec_diff_ref
  )
  
c1
c2
```


```{r}
# check if there are different columns
cc_out <- compare_cols(c1, c2)

# if there were different columns, add dummy columns as needed
c_list <- insert_dummy_cols(c1, c2, cc_out, id_cols)

# order columns
# c_list <- standardize_col_order(c_list$c1, c_list$c2, id_cols)
c1_s <- dplyr::select(c_list$c1, 
                      tidyselect::starts_with("id"), 
                      dec_diff_ref, dec_diff,
                      num, char, int, log, date, 
                      class_num_char, class_num_log
                      # , tidyselect::starts_with("extra")
                      )
c2_s <- dplyr::select(c_list$c2, tidyselect::all_of(colnames(c1_s)))
c1_s
c2_s
```

```{r}
# find duplicates
(dup_list1 <- find_dups(c1_s, id_cols))
(dup_list2 <- find_dups(c2_s, id_cols))
```


```{r}
# compare data frames on de-duplicated data only
comp <- compareDF_custom(dup_list1$no_dups, dup_list2$no_dups, id_cols)
comp$comparison_df
comp$comparison_table_diff
```


```{r}
# segregate the comparison and format the results
comp_list <- segregate_compare(comp$comparison_df)
comp_list
```



```{r}
# summarize differences between new and old
summarize_compare_rows(c1, 
                       c2, 
                       comp_list$adds, 
                       comp_list$dels, 
                       comp_list$chng_lr, 
                       comp_list$unchng, 
                       dup_list1, 
                       dup_list2,
                       id_cols)
```


```{r}
#' Summary metrics for data frame comparison by columns
#' 
#' Creates two data frames that summarize the differences by columns for two 
#' versions of the same data frame. The first provides higher level summary 
#' statistics on the number of columns in each data frame, the number of columns 
#' with changes, and the number of columns that have the same name but 
#' different classes. The second data frame lists by column the number of 
#' changes, whether the column was included in the new and/or old data frame, 
#' and the original column class.
#' 
#' @inheritParams compare_cols
#' @inheritParams insert_dummy_cols
#' @param comp_comparison_table_diff the `comparison_table_diff` element of a 
#' [compareDF::compare_df()] or [compareDF_custom()] output.
#' 
#' @returns a named list containing two data frames:
#'  * `report_simple` a data frame with higher level summary statistics
#'  * `report_by_col` a data frame that lists summary statistics by column name
#' @export
#' 
summarize_compare_cols <- function (c1, 
                                    c2, 
                                    cc_out, 
                                    id_cols, 
                                    comp_comparison_table_diff) {
  
  col_chng_cnts <- comp_comparison_table_diff %>%
    dplyr::select(-c(grp, chng_type)) %>%
    apply(2, function(x) sum(x == "+"))
  
  col_class1 <- colnames(c1) %>%
    setNames(colnames(c1)) %>%
    purrr::map(\(x) class(c1[[x]])) %>%
    unlist()
  
  col_class2 <- colnames(c2) %>%
    setNames(colnames(c2)) %>%
    purrr::map(\(x) class(c2[[x]])) %>%
    unlist()
  
  col_class_diff_cnt <- sum(col_class1 != col_class2)
  
  # report comparing new to old
  report_simple <- tibble::tribble(
    ~ Columns          , ~ New             , ~ Old             ,
    "Total"            , ncol(c1)          , ncol(c2)          ,
    "Changed"          , col_chng_cnts     , col_chng_cnts     ,
    "Different classes", col_class_diff_cnt, col_class_diff_cnt,
  )
  
  report_by_col
  
  return(
    list(
      
    )
  )
}
```












